var animals = [
  {
    name: "Curious George",
    herpes: true,
    price: 40000,
    img: "https://i1.sndcdn.com/artworks-t96S71fPBRmBZ1z4-drdGJw-t500x500.jpg",
    sus: "yes",
    lightskin: false,
  },
  {
    name: "Ernie",
    herpes: false,
    price: 0.5,
    img: "https://media.tenor.com/images/3751f40cc947cb78df02546ef2ae6b34/tenor.png",
    sus: "no",
    lightskin: false,
  },
  {
    name: "Cookie Monster",
    herpes: false,
    price: 25000,
    img: "https://pbs.twimg.com/profile_images/1471414184407560194/7wOQeSlF_400x400.jpg",
    sus: "yes",
    lightskin: false,
  },
  {
    name: "Moto Moto",
    herpes: true,
    price: 6000,
    img: "http://images7.memedroid.com/images/UPLOADED334/6023daf3a8523.jpeg",
    sus: "no",
    lightskin: false,
  },
  {
    name: "Peppa Pig",
    herpes: false,
    price: 20,
    img: "https://i1.sndcdn.com/artworks-SpxBvcTo1cDQQxdg-2S83lA-t500x500.jpg",
    sus: "arguable",
    lightskin: false,
  },
  {
    name: "Boots",
    herpes: false,
    price: 10,
    img: "https://i5.walmartimages.com/asr/7787e3b8-db77-478a-af01-513a8664e653_1.b2061dfb3fcd407265c9a9571d9b2908.jpeg",
    sus: "argueable",
    lightskin: false,
  },
  {
    name: "Lightskin Dog",
    herpes: true,
    price: 20,
    img: "https://pbs.twimg.com/media/FYWf5ymXEAIBZRk.jpg",
    sus: "yes",
    lightskin: true,
  },
  {
    name: "Lightskin Dog's Uncle",
    herpes: true,
    price: 20,
    img: "https://i.pinimg.com/originals/81/fc/de/81fcde8073647cf2c69bcbcf277adb44.jpg",
    sus: "yes",
    lightskin: true,
  },
  {
    name: "Half Lightskin Dog",
    herpes: true,
    price: 20,
    img: "https://m.media-amazon.com/images/I/51RntoCHFYL.jpg",
    sus: "yes",
    lightskin: true,
  },
  {
    name: "Lightskin Lion",
    herpes: true,
    price: 80,
    img: "https://external-preview.redd.it/oC1xsQfoxAgW-JbtdP7VTHAq3qaE6WxrUqsDghqaTuU.png?format=pjpg&auto=webp&s=78f21ff58a430d03ca34cd98530331c403ee8bc4",
    sus: "yes",
    lightskin: true,
  },
  {
    name: "Lightskin Gorilla",
    herpes: true,
    price: 100,
    img: "https://allthatsinteresting.com/wordpress/wp-content/uploads/2013/06/Albino-Gorilla.jpg",
    sus: "yes",
    lightskin: true,
  },
  {
    name: "Doge",
    herpes: false,
    price: 499.99,
    img: "https://i.ytimg.com/vi/T72xBrG8jk0/maxresdefault.jpg",
    sus: "argueable",
    lightskin: false,
  },
  {
    name: "Pepe",
    herpes: false,
    price: 0,
    img: "https://media.vanityfair.com/photos/5f5156490ca7fe28f9ec3f55/1:1/w_1333,h_1333,c_limit/feels-good-man-film.jpg",
    sus: "no",
    lightskin: false,
  },
  {
    name: "Quack",
    herpes: true,
    price: 100000,
    img: "https://resizing.flixster.com/VENcuXSukEf_jSuULNA_b9aA6Mw=/206x305/v2/https://flxt.tmsimg.com/assets/p2965542_e_v8_aa.jpg",
    sus: "no",
    lightskin: false,
  },
];

export { animals };
